<?php

/**
 * @file
 * Implementation of the Feeds mapping API for the media module.
 */

/**
 * Implements hook_feeds_processor_targets_alter().
 */
function media_feeds_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  if ($bundle_name === NULL) {
    return;
  }

  foreach (field_info_instances($entity_type, $bundle_name) as $name => $instance) {
    $info = field_info_field($name);

    if ($info['type'] == 'media') {
      $targets[$name] = array(
        'name' => t('@label (media_internet)', array('@label' => $instance['label'])),
        'callback' => 'media_feeds_set_internet_target',
        'description' => t('The @label field of the node. Value to be claimed by a Media Internet Sources provider. Be careful! The importing user will not need the @permission permission.', array('@label' => $instance['label'], '@permission' => 'add media from remote sources')),
      );
    }
  }
}

/**
 * Callback for mapping an URL or embed code to a field using media_internet.
 * The actual mapping happens here.
 */
function media_feeds_set_internet_target($source, $entity, $target, $values) {
  if (empty($values)) {
    return;
  }

  if (!is_array($values)) {
    $values = array($values);
  }

  $field_info = field_info_field($target);
  $field = array(LANGUAGE_NONE => array());

  foreach ($values as $value) {
    try {
      // Explicit support for FeedsEnclosure
      if ($value instanceof FeedsEnclosure) {
        $value = $value->getValue();
      }

      // Find a provider to create a file object
      $provider = media_internet_get_provider($value);

      // Wrap the provider to use some workarounds
      $provider = new MediaFeedsProviderWrapper($provider);

      // Validate and get a file object
      $provider->validate();
      $file = $provider->getFileObject();
      if (!$file) {
        drupal_set_message(t('Failed to get the file object.'));
        continue;
      }

      // Look for the field instance settings
      $instance = field_info_instance($entity->feeds_item->entity_type, $target, $entity->type);
      $allowed_types = $instance['widget']['settings']['allowed_types'];
      $allowed_schemes = $instance['widget']['settings']['allowed_schemes'];

      // Validate the type
      $errors = media_file_validate_types($file, $allowed_types);
      if (count($errors)) {
        foreach ($errors as $error) {
          drupal_set_message(filter_xss($error), 'error');
        }
        continue;
      }

      // Validate the URI scheme
      // If public is allowed also allow schemes supported by
      // MediaInternetFileHandler (http, ...)
      if (in_array('public', $allowed_schemes)) {
        $fromurlschemes = media_variable_get('fromurl_supported_schemes');
        foreach ($fromurlschemes as $fromurlscheme) {
          $allowed_schemes[$fromurlscheme] = $fromurlscheme;
        }
      }
      $scheme = file_uri_scheme($file->uri);
      if (!in_array($scheme, $allowed_schemes)) {
        drupal_set_message(t('Scheme %scheme not allowed for %target.', array('%scheme' => $scheme . '://', '%target' => $target)), 'error');
        continue;
      }

      // Save file
      $file = $provider->save();
      if (!$file) {
        drupal_set_message(t('Failed to save the file.'), 'error');
        continue;
      }

      // Apply author settings to the file
      if ((empty($file->uid) && !empty($entity->uid)) || $file->uid != $entity->uid) {
        $file->uid = $entity->uid;
        if (!file_save($file)) {
          drupal_set_message(t('Failed to apply the author settings to the file.'), 'warning');
        }
      }

      // Attach the file to the field
      $field[LANGUAGE_NONE][]['fid'] = $file->fid;
    } catch (MediaInternetNoHandlerException $e) {
      drupal_set_message($e->getMessage(), 'error');
    } catch (MediaInternetValidationException $e) {
      drupal_set_message($e->getMessage(), 'error');
    }
  }

  $entity->{$target} = $field;
}

/**
 * Implements hook_file_presave().
 */
function media_feeds_file_presave($file) {
  if (class_exists('MediaFeedsProviderWrapper', FALSE)) {
    if (MediaFeedsProviderWrapper::$currentExistingFile) {
      $file->fid = MediaFeedsProviderWrapper::$currentExistingFile;
      $file->is_new = FALSE;
    }
  }
}
